apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-platform-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-platform-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-platform-api
    spec:
      containers:
        - name: platform-api
          image: "{{ .Values.platformApi.image.repository }}:{{ .Values.platformApi.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.platformApi.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.platformApi.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ASPNETCORE_URLS
              value: {{ .Values.platformApi.env.ASPNETCORE_URLS | quote }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.platformApi.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.platformApi.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-platform-api
spec:
  selector:
    app: {{ .Release.Name }}-platform-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.platformApi.port }}
  type: {{ .Values.service.type }}
