@* <auto-generated>
   Generated from {{ApiPath}} at {{GeneratedAt:o}}
   DO NOT EDIT.
</auto-generated> *@
@page "{{RoutePrefix}}/{{RouteSegment}}/{{Id}}"
@attribute [Authorize(Policy = "{{Policy}}")]
@inject IApiClient Api

<PageTitle>{{DisplayName}} Detail</PageTitle>

<RadzenCard>
    <RadzenStack Orientation="Orientation.Horizontal" JustifyContent="JustifyContent.SpaceBetween" Class="rz-mb-4">
        <RadzenText TextStyle="TextStyle.H6">{{DisplayName}} Detail</RadzenText>
        <RadzenStack Gap="0.5rem">
            @if ({{HasUpdate}}) {
                <RadzenButton Icon="edit" Text="Edit" Click="@Edit" ButtonStyle="ButtonStyle.Primary" />
            }
            @if ({{HasDelete}}) {
                <RadzenButton Icon="delete" Text="Delete" ButtonStyle="ButtonStyle.Danger" Click="@ConfirmDelete" />
            }
            <RadzenButton Icon="arrow_back" Text="Back" Click="@GoBack" ButtonStyle="ButtonStyle.Secondary" />
        </RadzenStack>
    </RadzenStack>

    <ApiGate T="{{DtoType}}" Fetcher="@(ct => LoadAsync(ct))">
        <ChildContent Context="item">
{{#each Properties}}
            <RadzenStack Orientation="Orientation.Horizontal" Gap="1rem" Class="rz-mb-2">
                <RadzenText TextStyle="TextStyle.Body2" Style="min-width: 150px; font-weight: 500;">{{DisplayName}}:</RadzenText>
                <RadzenText TextStyle="TextStyle.Body2">@item.{{CSharpName}}</RadzenText>
            </RadzenStack>
{{/each}}
        </ChildContent>
    </ApiGate>
</RadzenCard>

@code {
    [Parameter] public string Id { get; set; } = "";
    private {{DtoType}}? _item;

    private async Task<{{DtoType}}> LoadAsync(CancellationToken ct)
    {
        var r = await Api.GetAsync<{{DtoType}}>($"{{ApiPath}}/{{Id}}", ct);
        if (!r.IsSuccess) throw new InvalidOperationException(r.Error!.Message);
        _item = r.Value!;
        return _item;
    }

    private void Edit() => _dialog?.OpenAsync<{{DtoType}}>("Edit {{DisplayName}}", typeof({{UpdateRequestType}}),
        new Dictionary<string, object?> { ["Mode"] = "Edit", ["Item"] = _item });

    private async Task ConfirmDelete()
    {
        var confirmed = await _dialog!.Confirm("Delete {{DisplayName}}?",
            "This action cannot be undone.", "Delete", "Cancel");
        if (!confirmed) return;
        var r = await Api.DeleteAsync($"{{ApiPath}}/{{Id}}");
        if (!r.IsSuccess) return;
        GoBack();
    }

    private void GoBack() => Nav.NavigateTo("{{RoutePrefix}}/{{RouteSegment}}");

    [Inject] private NavigationManager Nav { get; set; } = default!;
    [Inject] private RadzenDialog? _dialog { get; set; }
}