@* <auto-generated>
   Generated from {{ApiPath}} at {{GeneratedAt:o}}
   DO NOT EDIT.
</auto-generated> *@
@inject IApiClient Api

<RadzenTemplateForm TItem="{{RequestType}}" Data="@_model" Submit="@OnSubmit">
    <DataAnnotationsValidator />
    <RadzenStack Gap="1rem">
{{#each Properties}}
        <RadzenFormField Text="{{DisplayName}}" Variant="Variant.Outlined">
            {{#if IsEnum}}
            <RadzenSelect @bind-Value="_model.{{CSharpName}}">
                @foreach (var v in Enum.GetValues<{{EnumType}}>())
                {
                    <RadzenSelectItem Value="v" Text="@v.ToString()" />
                }
            </RadzenSelect>
            {{/if}}
            {{#if IsBool}}
            <RadzenCheckBox @bind-Value="_model.{{CSharpName}}" TValue="bool" />
            {{/if}}
            {{#if IsString}}
            <RadzenTextBox @bind-Value="_model.{{CSharpName}}" />
            {{/if}}
            {{#if IsNumeric}}
            <RadzenNumeric @bind-Value="_model.{{CSharpName}}" TValue="{{ClrType}}" />
            {{/if}}
            {{#if IsDate}}
            <RadzenDatePicker @bind-Value="_model.{{CSharpName}}" TValue="{{ClrType}}" />
            {{/if}}
        </RadzenFormField>
{{/each}}
        <RadzenStack Orientation="Orientation.Horizontal" JustifyContent="JustifyContent.End" Gap="0.5rem">
            <RadzenButton ButtonType="ButtonType.Button" Text="Cancel" Click="@OnCancel" />
            <RadzenButton ButtonType="ButtonType.Submit" Text="Save" ButtonStyle="ButtonStyle.Primary" Disabled="@_saving" />
        </RadzenStack>
    </RadzenStack>
</RadzenTemplateForm>

@code {
    [Parameter] public string Mode { get; set; } = "Create";
    [Parameter] public {{DtoType}}? Item { get; set; }
    [Parameter] public EventCallback OnSaved { get; set; }
    [Parameter] public EventCallback OnCancelled { get; set; }

    private {{RequestType}} _model = new();
    private bool _saving;

    protected override void OnParametersSet()
    {
        if (Mode == "Edit" && Item is not null)
            _model = MapToRequest(Item);
    }

    private async Task OnSubmit()
    {
        _saving = true;
        try
        {
            Result<{{DtoType}}> r;
            if (Mode == "Create")
                r = await Api.PostAsync<{{DtoType}}>("{{ApiPath}}", _model,
                    idempotencyKey: Guid.NewGuid().ToString("N"));
            else
                r = await Api.PutAsync<{{DtoType}}>($"{{ApiPath}}/{GetId(Item!)}", _model);

            if (r.IsSuccess) await OnSaved.InvokeAsync();
        }
        finally { _saving = false; }
    }

    private async Task OnCancel() => await OnCancelled.InvokeAsync();

    private static {{RequestType}} MapToRequest({{DtoType}} dto)
    {
        return new {{RequestType}}(
{{#each RequestParameters}}
            dto.{{SourceProperty}}{{^last}},{{/last}}
{{/each}}
        );
    }

    private static string GetId({{DtoType}} row) =>
        row.GetType().GetProperty("Id")!.GetValue(row)!.ToString()!;
}