@* <auto-generated>
   Generated from {{ApiPath}} at {{GeneratedAt:o}}
   Source: {{SourceMapPath}}
   DO NOT EDIT. Regenerate via: dotnet build -p:GenerateApiPages=true
</auto-generated> *@
@page "{{RoutePrefix}}/{{RouteSegment}}"
@attribute [Authorize(Policy = "{{Policy}}")]
@inject IApiClient Api

<PageTitle>{{DisplayName}}</PageTitle>

<RadzenCard>
    <RadzenStack Orientation="Orientation.Horizontal" JustifyContent="JustifyContent.SpaceBetween" Class="rz-mb-4">
        <RadzenText TextStyle="TextStyle.H6">{{DisplayName}}</RadzenText>
        @if ({{HasCreate}}) {
            <RadzenButton Icon="add" Text="New" Click="@OpenCreateDialog" ButtonStyle="ButtonStyle.Primary" />
        }
    </RadzenStack>

    <ApiGate T="PagedResult<{{DtoType}}>"
             Fetcher="@(ct => LoadPageAsync(_page, _size, _sort, ct))">
        <ChildContent Context="page">
            <RadzenDataGrid Data="@page.Items" TItem="{{DtoType}}"
                            AllowPaging="true" PageSize="@_size"
                            Count="@page.Total"
                            LoadData="@OnLoadData">
                <Columns>
{{#each Properties}}
                    <RadzenDataGridColumn TItem="{{DtoType}}"
                                          Property="{{CSharpName}}"
                                          Title="{{DisplayName}}"
                                          {{#if IsSortable}}Sortable="true"{{/if}}
                                          {{#if IsFilterable}}Filterable="true"{{/if}} />
{{/each}}
                    <RadzenDataGridColumn TItem="{{DtoType}}" Title="Actions" Sortable="false" Filterable="false">
                        <Template Context="row">
                            @if ({{HasUpdate}}) {
                                <RadzenButton Icon="edit" Size="ButtonSize.Small" Click="@(() => OpenEditDialog(row))" />
                            }
                            @if ({{HasDelete}}) {
                                <RadzenButton Icon="delete" Size="ButtonSize.Small" ButtonStyle="ButtonStyle.Danger"
                                              Click="@(() => ConfirmDelete(row))" />
                            }
                        </Template>
                    </RadzenDataGridColumn>
                </Columns>
            </RadzenDataGrid>
        </ChildContent>
    </ApiGate>
</RadzenCard>

@if ({{HasCreate}} || {{HasUpdate}}) {
    <RadzenDialog @ref="_dialog" />
}

@code {
    private const int DefaultPageSize = 20;
    private int _page = 1;
    private int _size = DefaultPageSize;
    private string? _sort;
    private RadzenDialog? _dialog;

    private async Task<PagedResult<{{DtoType}}>> LoadPageAsync(int page, int size, string? sort, CancellationToken ct)
    {
        var query = new Dictionary<string, object?> { ["page"] = page, ["size"] = size };
        if (!string.IsNullOrEmpty(sort)) query["sort"] = sort;
        var r = await Api.GetAsync<PagedResult<{{DtoType}}>>("{{ApiPath}}", query, ct);
        if (!r.IsSuccess) throw new InvalidOperationException(r.Error!.Message);
        return r.Value!;
    }

    private async Task OnLoadData(LoadDataArgs args)
    {
        _page = (args.Skip ?? 0) / (args.Top ?? DefaultPageSize) + 1;
        _size = args.Top ?? DefaultPageSize;
        _sort = args.OrderBy;
        await InvokeAsync(StateHasChanged);
    }

{{#if HasCreate}}
    private async Task OpenCreateDialog()
    {
        await _dialog!.OpenAsync<{{DtoType}}>("Create {{DisplayName}}", typeof({{CreateRequestType}}),
            new Dictionary<string, object?> { ["Mode"] = "Create" });
    }
{{/if}}

{{#if HasUpdate}}
    private async Task OpenEditDialog({{DtoType}} row)
    {
        await _dialog!.OpenAsync<{{DtoType}}>("Edit {{DisplayName}}", typeof({{UpdateRequestType}}),
            new Dictionary<string, object?> { ["Mode"] = "Edit", ["Item"] = row });
    }
{{/if}}

{{#if HasDelete}}
    private async Task ConfirmDelete({{DtoType}} row)
    {
        var confirmed = await _dialog!.Confirm("Delete {{DisplayName}}?",
            "This action cannot be undone.", "Delete", "Cancel");
        if (!confirmed) return;
        var r = await Api.DeleteAsync($"{{ApiPath}}/{GetId(row)}");
        if (!r.IsSuccess)
        {
            return;
        }
        await InvokeAsync(StateHasChanged);
    }

    private static string GetId({{DtoType}} row) =>
        row.GetType().GetProperty("Id")!.GetValue(row)!.ToString()!;
{{/if}}
}