@* <auto-generated> Navigation fragments from x-admin-ui. DO NOT EDIT. </auto-generated> *@
@namespace {{Namespace}}

@code {
    public static class GeneratedAdminNav
    {
        public static readonly NavItem[] Items =
        [
{{#each Resources}}
            new("{{DisplayName}}", "{{RoutePrefix}}/{{RouteSegment}}", "{{Icon}}", {{Order}}),
{{/each}}
        ];
    }

    public sealed record NavItem(string Label, string Href, string Icon, int Order);
}