apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: [service_name, pod]
        mappedTags: [{ key: service.name, value: service_name }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: service.name, value: service }]
        queries:
          - name: Request rate
            query: 'sum(rate(http_server_request_duration_seconds_count{$$__tags}[5m]))'
          - name: Error rate
            query: 'sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~"5..",$$__tags}[5m]))'
      serviceMap:
        datasourceUid: prometheus
        nodeGraph:
          enabled: true
      lokiSearch:
        datasourceUid: loki