import { Command } from "commander";
import { writeFileSync, existsSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { confirm } from "@inquirer/prompts";
import chalk from "chalk";
import ora from "ora";
import { getAll } from "../lib/store.js";
import { generateSecret } from "../lib/secrets.js";

const PLACEHOLDER_MARK = "# Generated by halalchain-cli — do not commit. ALL values are NON-PRODUCTION placeholders.\n";

function buildRootEnv(cfg) {
  const key = cfg["jwt.key"] || generateSecret(32);
  return [
    PLACEHOLDER_MARK,
    `JWT__KEY=${key}`,
    `AI_GATEWAY_API_KEY=`,
    `ASPNETCORE_ENVIRONMENT=Development`,
    `POSTGRES_CONNECTION_STRING=Host=postgres;Database=halalchain;Username=halalchain;Password=CHANGE_ME_BEFORE_DEPLOY`,
    `REDIS_CONNECTION_STRING=redis:6379`,
    "",
  ].join("\n");
}

function buildTawheedEnv(cfg) {
  const key = cfg["jwt.key"] || generateSecret(32);
  return [
    PLACEHOLDER_MARK,
    `DEMO_MODE=true`,
    `ENVIRONMENT=development`,
    `POSTGRES_URL=postgresql+asyncpg://tawheed:CHANGE_ME_BEFORE_DEPLOY@postgres:5432/tawheed`,
    `REDIS_URL=redis://redis:6379/0`,
    `QDRANT_URL=http://qdrant:6333`,
    `QDRANT_COLLECTION=halal_knowledge`,
    `NEO4J_URI=bolt://neo4j:7687`,
    `NEO4J_USER=neo4j`,
    `NEO4J_PASSWORD=CHANGE_ME_BEFORE_DEPLOY`,
    `LLM_PROVIDER=demo`,
    `LLM_API_KEY=`,
    `LLM_MODEL=gpt-4o-mini`,
    `LLM_BASE_URL=`,
    `JWT_SECRET=${key}`,
    `JWT_ALGORITHM=HS256`,
    `JWT_EXPIRE_MINUTES=60`,
    `OTLP_ENDPOINT=http://localhost:4317`,
    `DEFAULT_POLICY_VERSION=${cfg["tawheed.policy-version"] || "MY-v3"}`,
    `DEFAULT_JURISDICTION=${cfg["tawheed.jurisdiction"] || "MY"}`,
    `RISK_THRESHOLD_MANUAL_REVIEW=0.65`,
    `RISK_THRESHOLD_HOLD=0.85`,
    "",
  ].join("\n");
}

export function envCommand() {
  const cmd = new Command("env").description("Generate and validate .env files from config");

  cmd.command("generate")
    .description("Write .env files for docker compose and tawheed")
    .option("--cwd <path>", "Project root directory", process.cwd())
    .option("--force", "Overwrite without prompting")
    .action(async (opts) => {
      const cfg = getAll();
      const files = [
        { label: "root (.env)", path: join(opts.cwd, ".env"), content: buildRootEnv(cfg) },
        { label: "tawheed (.env)", path: join(opts.cwd, "tawheed", ".env"), content: buildTawheedEnv(cfg) },
      ];
      for (const file of files) {
        if (!opts.force && existsSync(file.path)) {
          const ok = await confirm({ message: `${file.path} already exists. Overwrite?`, default: false });
          if (!ok) { console.log(chalk.dim(`  Skipped ${file.label}`)); continue; }
        }
        writeFileSync(file.path, file.content, "utf8");
        // Restrict file permissions on POSIX so generated .env files are not
        // world-readable. 0600 (rw for owner only).
        try { chmodSync(file.path, 0o600); } catch { /* non-POSIX or read-only fs */ }
        console.log(chalk.green(`  ✔ Written ${file.label} → ${file.path} (0600)`));
      }
    });

  cmd.command("check")
    .description("Ping all configured services and report status")
    .action(async () => {
      const cfg = getAll();
      const services = [
        { name: "Platform API  ", url: cfg["platform-api.url"] + "/health/live", method: "GET" },
        { name: "Marketplace   ", url: cfg["marketplace.url"] + "/health/live", method: "GET" },
        { name: "AI Inference  ", url: cfg["ai-inference.url"] + "/health/live", method: "GET" },
        { name: "Tawheed       ", url: cfg["tawheed.url"] + "/health", method: "GET" },
      ];
      console.log(chalk.bold("\n  Service health check\n"));
      for (const svc of services) {
        const spinner = ora({ text: svc.name, prefixText: "  " }).start();
        try {
          const res = await fetch(svc.url, {
            method: svc.method,
            signal: AbortSignal.timeout(4000),
          });
          res.ok
            ? spinner.succeed(chalk.green(svc.name) + chalk.dim(` ${res.status} ${svc.url}`))
            : spinner.fail(chalk.red(svc.name) + chalk.dim(` ${res.status} ${svc.url}`));
        } catch (err) {
          spinner.fail(chalk.red(svc.name) + chalk.dim(` unreachable — ${err.message}`));
        }
      }
      console.log();
    });

  return cmd;
}
