import { Command } from 'commander'
import { chmodSync, existsSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { confirm } from '@inquirer/prompts'
import chalk from 'chalk'
import { getAll } from '../lib/config.js'
import { generateSecret } from '../lib/secrets.js'

const PLACEHOLDER_MARK =
  '# Generated by `halalchain env generate` — do not commit.\n' +
  '# Every value below is a NON-PRODUCTION placeholder.\n'

/** Placeholder that forces an operator to supply a real secret before deploy. */
const CHANGE_ME = 'CHANGE_ME_BEFORE_DEPLOY'

function buildRootEnv(cfg: Record<string, string>): string {
  const key = cfg['jwt.key'] || generateSecret(32)
  return [
    PLACEHOLDER_MARK,
    `JWT__KEY=${key}`,
    `JWT__ISSUER=${cfg['jwt.issuer'] ?? 'HalalChainPlatform'}`,
    `JWT__AUDIENCE=${cfg['jwt.audience'] ?? 'HalalChainClients'}`,
    `JWT__EXPIRES_MINUTES=${cfg['jwt.expires-minutes'] ?? '60'}`,
    `AI_GATEWAY_API_KEY=${cfg['ai-inference.api-key'] ?? ''}`,
    'ASPNETCORE_ENVIRONMENT=Development',
    `POSTGRES_CONNECTION_STRING=Host=postgres;Database=halalchain;Username=halalchain;Password=${CHANGE_ME}`,
    'REDIS_CONNECTION_STRING=redis:6379',
    '',
  ].join('\n')
}

function buildTawheedEnv(cfg: Record<string, string>): string {
  const key = cfg['jwt.key'] || generateSecret(32)
  return [
    PLACEHOLDER_MARK,
    'DEMO_MODE=true',
    'ENVIRONMENT=development',
    `POSTGRES_URL=postgresql+asyncpg://tawheed:${CHANGE_ME}@postgres:5432/tawheed`,
    'REDIS_URL=redis://redis:6379/0',
    'QDRANT_URL=http://qdrant:6333',
    'QDRANT_COLLECTION=halal_knowledge',
    'NEO4J_URI=bolt://neo4j:7687',
    'NEO4J_USER=neo4j',
    `NEO4J_PASSWORD=${CHANGE_ME}`,
    'LLM_PROVIDER=demo',
    'LLM_API_KEY=',
    'LLM_MODEL=gpt-4o-mini',
    'LLM_BASE_URL=',
    `JWT_SECRET=${key}`,
    'JWT_ALGORITHM=HS256',
    'JWT_EXPIRE_MINUTES=60',
    'OTLP_ENDPOINT=http://localhost:4317',
    `DEFAULT_POLICY_VERSION=${cfg['tawheed.policy-version'] || 'MY-v3'}`,
    `DEFAULT_JURISDICTION=${cfg['tawheed.jurisdiction'] || 'MY'}`,
    'RISK_THRESHOLD_MANUAL_REVIEW=0.65',
    'RISK_THRESHOLD_HOLD=0.85',
    '',
  ].join('\n')
}

export function createEnvCommand(): Command {
  const cmd = new Command('env').description('Generate and validate .env files from config')

  cmd
    .command('generate')
    .description('Write .env files for docker compose and the tawheed service')
    .option('--cwd <path>', 'Repository root', process.cwd())
    .option('--force', 'Overwrite without prompting')
    .action(async (opts: { cwd: string; force?: boolean }) => {
      const cfg = getAll()
      const files = [
        { label: 'root        (.env)', path: join(opts.cwd, '.env'), content: buildRootEnv(cfg) },
        // The service lives at .halalchain/tawheed, not ./tawheed. The legacy
        // command wrote to the wrong path and produced a file nothing read.
        {
          label: 'tawheed     (.halalchain/tawheed/.env)',
          path: join(opts.cwd, '.halalchain', 'tawheed', '.env'),
          content: buildTawheedEnv(cfg),
        },
      ]

      for (const file of files) {
        if (!opts.force && existsSync(file.path)) {
          const ok = await confirm({ message: `${file.path} already exists. Overwrite?`, default: false })
          if (!ok) {
            console.log(chalk.dim(`  Skipped ${file.label}`))
            continue
          }
        }
        writeFileSync(file.path, file.content, 'utf8')
        // 0600 on POSIX: these files carry a real JWT secret.
        try {
          chmodSync(file.path, 0o600)
        } catch {
          /* non-POSIX or read-only fs */
        }
        console.log(chalk.green(`  ✔ Written ${file.label} → ${file.path} (0600)`))
      }
    })

  cmd
    .command('check')
    .description('Ping every configured service and report status')
    .action(async () => {
      const cfg = getAll()
      const services: { name: string; url: string; path: string }[] = [
        { name: 'Platform API ', url: cfg['platform-api.url'] ?? '', path: '/health/live' },
        { name: 'Marketplace  ', url: cfg['marketplace.url'] ?? '', path: '/health' },
        { name: 'Customer UI  ', url: cfg['halalchain.url'] ?? '', path: '/health' },
        { name: 'AI Gateway   ', url: cfg['ai-inference.url'] ?? '', path: '/health/live' },
        { name: 'Policy Engine', url: cfg['tawheed.url'] ?? '', path: '/health' },
        { name: 'Local Models ', url: cfg['local-models.url'] ?? '', path: '/health/live' },
        { name: 'Agents       ', url: cfg['agents.url'] ?? '', path: '/health/live' },
      ]

      console.log(chalk.bold('\n  Service health check\n'))
      let down = 0
      for (const svc of services) {
        const target = svc.url + svc.path
        try {
          const res = await fetch(target, {
            method: 'GET',
            signal: AbortSignal.timeout(4000),
          })
          if (res.ok) {
            console.log(`  ${chalk.green('✔')} ${chalk.green(svc.name)} ${chalk.dim(`${res.status} ${target}`)}`)
          } else {
            down += 1
            console.log(`  ${chalk.red('✖')} ${chalk.red(svc.name)} ${chalk.dim(`${res.status} ${target}`)}`)
          }
        } catch (err) {
          down += 1
          console.log(`  ${chalk.red('✖')} ${chalk.red(svc.name)} ${chalk.dim(`unreachable — ${(err as Error).message}`)}`)
        }
      }
      console.log()
      if (down > 0) {
        console.log(chalk.dim(`  ${down} service(s) unreachable. Try: docker compose up --build\n`))
      }
    })

  return cmd
}
